pull_request_title: 'chore(l10n): update translations from Crowdin'
files:
  - source: /packages/@divvi/mobile/locales/base/*.json
    translation: /packages/@divvi/mobile/locales/%locale%/%original_file_name%
    type: i18next_json
