name: Release

on:
  workflow_run:
    # TODO: consider doing this only if the e2e tests succeeded
    workflows: ['Test']
    types:
      - completed

jobs:
  publish:
    name: ${{ github.ref == 'refs/heads/main' && 'Publish' || 'Publish (dry-run)' }}
    # Only run if the test workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v4
        with:
          # Full git history is needed for release notes
          fetch-depth: 0
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.MAINNET_SERVICE_ACCOUNT_KEY }}
      - id: google-secrets
        uses: google-github-actions/get-secretmanager-secrets@v2
        with:
          secrets: |-
            NPM_TOKEN:celo-mobile-mainnet/NPM_TOKEN
            SLACK_WEBHOOK_URL:celo-mobile-mainnet/SLACK_ONCALL_WEBHOOK_URL
      - uses: ./.github/actions/yarn-install
      - name: Publish to NPM
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            yarn release
          else
            # Dry run to ensure it still works in case of deps changes
            yarn release --dry-run
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ steps.google-secrets.outputs.NPM_TOKEN }}
